services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - my_site/.env
    volumes:
      - .:/my_site
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    expose:
      - "5432"
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
    - ./data/db:/var/lib/postgresql/data
